### ISSUE TITLE
Unable to link with discord profile

### ISSUE THREAD

**Issue by Velloria** [Mayerch1/TheDiscordSoundboard#12] opened 2019-02-27 04:32 UTC
Followed all steps to create bot successfully
Added bot to server
Added Username 

However
Program never seems to connect with Discord profile and I get an error message: "Cannot Find specified Owner. Please retry"

Not sure what else to check or how I can make this work

Windows 7 Ultimate x64

**Comment by Mayerch1** [comment] 2019-02-27 15:33
It seems like the application didn't resolve your user-ID from the entered username.

You can resolve this by forcing the application to reload your entered credentials. 

- Switch to the settings tab
- Select the field which contains your username
- Move your cursor to the last position and hit return.
- Restart the application, as the id is only loaded on startup

This will tell the application to refresh your user id.
_Note: This workaround might not be working in older versions (2.2.0 and below)_

I'll add a function to the application which checks for an invalid user-ID and then refreshes it while the program is running.

Please close the issue when your problem was solved 
and feel free to ask more questions if not.

**Comment by Mayerch1** [comment] 2019-03-21 17:49
Please reopen if the issue is still existing.

**Closed** 2019-03-21 17:48 UTC
